version: "3.8"

services:
  alarmservice:
    container_name: payment-service
    image: payment-service
    build:
      context: .
      target: development
    volumes:
      - .:/payment-service
    links:
      - postgres
    environment:
      - TEST_POSTGRES_DSN=postgres://chirpstack_as:letirev@postgres/chirpstack_as?sslmode=disable
    ports:
      - 9000:9000